name: Node.js CI
env: 
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_DIALECT: ${{ secrets.MYSQL_DIALECT }}
  BACKEND_PORT: ${{ secrets.BACKEND_PORT}}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Start server
      run: |
        cd backend
        npm start &
    
    - name: Run tests
      run: |
        cd backend
        npm test

